application: letsplantheevent
version: production
runtime: python
api_version: 1

skip_files:
- ^(.*/)?(dojo|dojox|dijit)(.*)

builtins:
- deferred: on

handlers:
- url: /img
  static_dir: static/img

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: .*
  script: main.py
