application: eventplanner
version: 1
runtime: python
api_version: 1

handlers:
- url: /img
  static_dir: static/img

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: .*
  script: main.py
